autoload -U colors && colors

POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_DELIMITER="..."
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_rvm_version context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status ram)
POWERLEVEL9K_MODE='awesome-patched'

POWERLEVEL9K_CUSTOM_RVM_VERSION="rvm_version"
POWERLEVEL9K_CUSTOM_RVM_VERSION_BACKGROUND="red"
POWERLEVEL9K_CUSTOM_RVM_VERSION_FOREGROUND="white"

ZSH_THEME="powerlevel9k/powerlevel9k"
